# Generated by Django 2.0.1 on 2018-01-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='title_text',
            field=models.CharField(default='just a bunch of numbers', max_length=100),
        ),
    ]
