# Generated by Django 2.0.1 on 2018-02-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_addition_title_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Yet another book', max_length=150)),
                ('author', models.CharField(default='By yet another author', max_length=100)),
                ('release', models.DateField()),
                ('description', models.CharField(default='Description for the book', max_length=500)),
            ],
        ),
    ]
