# Generated by Django 2.0.1 on 2018-02-20 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20180220_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wager',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Book'),
        ),
        migrations.AlterField(
            model_name='wager',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wager',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getter', to=settings.AUTH_USER_MODEL),
        ),
    ]
