# Generated by Django 2.0.1 on 2018-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_wager_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wager',
            name='status',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
