# Generated by Django 2.0.1 on 2018-02-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20180221_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='release',
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
