# Generated by Django 2.0.1 on 2018-03-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_wager_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='bet',
            field=models.IntegerField(default=5),
        ),
    ]
