# Generated by Django 2.0.1 on 2018-03-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_auto_20180302_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='received_end',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='wager',
            name='sender_end',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
