# Generated by Django 2.0.1 on 2018-03-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0033_auto_20180308_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favourite_book',
            new_name='favourite_books',
        ),
    ]
