# Generated by Django 2.0.1 on 2018-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_auto_20180309_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='received_discuss',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='wager',
            name='sender_discuss',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
