# Generated by Django 2.0.1 on 2018-03-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_wagerquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='questions',
            field=models.IntegerField(default=10),
        ),
    ]
