# Generated by Django 2.0.1 on 2018-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0041_auto_20180321_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='received_new_bet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wager',
            name='received_new_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='wager',
            name='sender_new_bet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wager',
            name='sender_new_duration',
            field=models.DurationField(null=True),
        ),
    ]
