# Generated by Django 2.0.1 on 2018-03-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0042_auto_20180321_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wager',
            name='until',
            field=models.DateTimeField(null=True),
        ),
    ]
