# Generated by Django 2.0.1 on 2018-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0045_wagerquestion_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='questions_checked',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='wager',
            name='questions_right',
            field=models.IntegerField(default=0),
        ),
    ]
