# Generated by Django 2.0.1 on 2018-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0046_auto_20180323_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='questions_answered',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
