# Generated by Django 2.1.5 on 2019-01-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0050_profile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(default='Новичок', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_experience',
            field=models.IntegerField(default=100),
        ),
    ]
