# Generated by Django 2.1.5 on 2019-01-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0051_auto_20190127_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
