# Generated by Django 2.1.5 on 2019-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0054_auto_20190130_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='By yet another author', max_length=600),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Yet another book', max_length=600),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
