# Generated by Django 2.0.1 on 2018-02-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addition',
        ),
    ]
