# Generated by Django 2.0.1 on 2018-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20180220_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
