# Generated by Django 2.0.1 on 2018-02-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20180220_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wager',
            name='status',
            field=models.CharField(default='none', max_length=5, null=True),
        ),
    ]
