# Generated by Django 2.0.1 on 2018-02-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20180226_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
