# Generated by Django 2.0.1 on 2018-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_profile_books_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_authors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_book',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_genres',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
