# Generated by Django 2.0.1 on 2018-03-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_auto_20180309_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='your question', max_length=150)),
                ('answer', models.CharField(default='your answer', max_length=150)),
                ('wager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Wager')),
            ],
        ),
    ]
