# Generated by Django 2.0.1 on 2018-03-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_auto_20180319_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wager',
            name='status',
        ),
        migrations.AddField(
            model_name='wager',
            name='received_status',
            field=models.CharField(default='true', max_length=10),
        ),
        migrations.AddField(
            model_name='wager',
            name='sender_status',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
