# Generated by Django 2.0.1 on 2018-03-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_auto_20180320_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wager',
            name='received_status',
        ),
        migrations.RemoveField(
            model_name='wager',
            name='sender_status',
        ),
        migrations.AddField(
            model_name='wager',
            name='status',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
